services:
  app:
    build: .
    container_name: bclicker-app
    depends_on:
      - database

  database:
    image: mysql:5.7
    container_name: bclicker-database
    environment:
      MYSQL_ROOT_PASSWORD: $SQL_PASSWORD
      MYSQL_USER: bc
      MYSQL_PASSWORD: $SQL_PASSWORD
      MYSQL_DATABASE: bclicker
    volumes:
      - db:/var/lib/mysql
      - ./database.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  db:
    driver: local

networks:
  default:
    name: nginx_default
    driver: bridge
