name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: sudo docker compose build --build-arg ENV=prod
    - name: Create and start container
      run: sudo docker compose create && sudo docker compose start
